config/routes.rb
Rails.application.routes.draw do

  resources :messages, only: [:new, :create]

  get 'static/sport'
  get 'static/terms'

  resources :categories, only: [:show, :index]
  resources :competitions, only: [:show, :index]
  resources :events, only: [:show, :index]
  resources :players, only: [:show]
  resources :tickets, only: [:show]

  root 'home#index'

  namespace :admin do
    root 'welcome#index'
    resources :categories
    resources :competitions
    resources :events
    resources :players
    resources :tickets
    resources :venues
  end

end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :venue
  belongs_to :category
  has_one :competition
  has_and_belongs_to_many :players
  has_many :tickets, dependent: :destroy

  validates :name, presence: true,
                   length: { maximum: 50 }
  validates :start_time, presence: true
  validates :venue_id, presence: true
  validates :category_id, presence: true
  validates :sports, inclusion: { in: [true, false] }
  validates :priority, inclusion: { in: [true, false] }

  include PgSearch
  pg_search_scope :search, :against => :name,
    using: {tsearch: {dictionary: "english"}},
    associated_against: {venue: [:name, :city], category: :description}

  def self.text_search(query)
    if query.present?
      search(query)
    else
      scoped
    end
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < AdminController

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(event_params)
    @players = Player.where(:id => params[:event_players])
    @event.players << @players

    if @event.save
      flash[:notice] = "Event successfully created"
      redirect_to [:admin, @event]
    else
      render 'new'
    end
  end

  def update
    @event = Event.find(params[:id])
    @players = Player.where(:id => params[:event_players])
    @event.players.destroy_all
    @event.players << @players

    if @event.update(event_params)
      flash[:notice] = "Event successfully updated"
      redirect_to [:admin, @event]
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    flash[:notice] = "Event successfully deleted"
    redirect_to admin_events_path
  end

  private

  def event_params
    params.require(:event).permit(:name, :start_time, :venue_id,
                                  :category_id, :competition_id,
                                  :sports, :priority)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.text_search(params[:query])
    @sorted = @events.sort { |a,b| a.start_time <=> b.start_time }
  end

  def show
    @event = Event.find(params[:id])
    @category = Category.find(@event.category_id)
    @category_description = Category.find(@event.category_id).description
    gon.latitude = @event.venue.latitude
    gon.longitude = @event.venue.longitude
    if params[:comp]
      @competition = Competition.find(params[:comp])
    elsif @event.competition_id != nil
      @competition = Competition.find(@event.competition_id)
    end
    if params[:player]
      @player = Player.find(params[:player])
    end
  end

end

app/views/admin/events/_form.html.erb
<%= form_for [:admin, @event] do |f| %>

  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@event.errors.count, "error") %> prohibited
        this event from being saved:
      </h2>
      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </p>

  <p>
    <%= f.label :venue_id %><br>
    <%= f.collection_select(:venue_id, Venue.order('name ASC'), :id, :name, prompt: true) %>
  </p>

  <p>
    <%= f.label :category_id %><br>
    <%= f.collection_select(:category_id, Category.order('description ASC'), :id, :description, prompt: true) %>
  </p>

  <p>
    <%= f.label :competition_id %><br>
    <%= f.collection_select(:competition_id, Competition.order('name ASC'), :id, :name, prompt: true) %>
  </p>

  <p>
    <%= f.label :sports, 'Is this event a sport?' %>
    <%= f.check_box :sports %>
  </p>

  <p>
    <%= f.label :priority, 'Do you want to prioritize this event?' %>
    <%= f.check_box :priority %>
  </p>

  <!-- habtm addition -->

  <p>
    <%= f.label :players %>
    <%= select_tag "event_players", options_from_collection_for_select(Player.all, 'id', 'name',@event.players.map{ |player| player.id }), :multiple => true %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/admin/events/edit.html.erb
<h2>Edit Event</h2>

<%= render 'form' %>

<%= link_to 'Back', admin_events_path %>

app/views/admin/events/index.html.erb
<h1>Listing Events</h1>

<%= link_to 'New event', new_admin_event_path, class: "pure-button" %>

<br />
<br />

<table class="pure-table pure-table-striped pure-table-horizontal">
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Start time</th>
    <th>Venue</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @events.each do |event| %>
    <tr>
      <td><%= event.id %></td>
      <td><%= event.name %></td>
      <td><%= event.start_time.strftime("%a, %d-%b-%Y at %I:%M%p") %></td>
      <td><%= Venue.find(event.venue_id).name %></td>
      <td><%= Category.find(event.category_id).description %></td>
      <td><%= link_to 'Show', admin_event_path(event) %></td>
      <td><%= link_to 'Edit', edit_admin_event_path(event) %></td>
      <td><%= link_to 'Destroy', admin_event_path(event),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/admin/events/new.html.erb
<h2>New Event</h2>

<%= render 'form' %>

<%= link_to 'Back', admin_events_path %>

app/views/admin/events/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @event.start_time.strftime("%a, %d-%b-%Y at %I:%M%p") %>
</p>

<p>
  <strong>Venue:</strong>
  <%= Venue.find(@event.venue_id).name %>
</p>

<p>
  <strong>Category:</strong>
  <%= Category.find(@event.category_id).description %>
</p>

<% if @event.competition_id != nil %>
  <p>
    <strong>Competition:</strong>
    <%= Competition.find(@event.competition_id).name %>
  </p>
  <% else %>
  <p>
    This event doesn't have a competition.
  </p>
<% end %>

<% if @event.players.count != 0 %>
  <p>
    <strong>Players:</strong><br />
    <% @event.players.each do |player| %>
      <%= player.name %><br />
    <% end %>
  </p>
  <% else %>
  <p>
    This event doesn't have any players.
  </p>
<% end %>

<%= link_to 'Edit', edit_admin_event_path(@event) %> |
<%= link_to 'Back', admin_events_path %>