config/routes.rb
Rails.application.routes.draw do

  resources :messages, only: [:new, :create]

  get 'static/sport'
  get 'static/terms'

  resources :categories, only: [:show, :index]
  resources :competitions, only: [:show, :index]
  resources :events, only: [:show, :index]
  resources :players, only: [:show]
  resources :tickets, only: [:show]

  root 'home#index'

  namespace :admin do
    root 'welcome#index'
    resources :categories
    resources :competitions
    resources :events
    resources :players
    resources :tickets
    resources :venues
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    # @sports = Event.where(sports: true).sample(3)
    # @concerts_id = Category.where(description: "Concerts").ids
    # @music = Event.where(category_id: @concerts_id).sample(3)
  end

end

app/views/home/index.html.erb
  <section id="homepage-hero">

    <div class="row">
      <div class="small-12 small-centered text-center medium-8 large-6 columns">
        <span class="hide-for-touch">
          <h1 class="gotham-bold">Ticket<span class="gotham-regular">Finders</span></h1><br>
        </span>
        <span class="show-for-touch">
          <h2 class="gotham-regular">Ticket<span class="gotham-light">Finders</span></h2><br>
        </span>
      </div>
    </div>
    <div class="row">
      <div class="small-12 small-centered text-center medium-7 large-6 columns">
        <div class="row collapse">
          <div class="small-1 columns">
            <span class="prefix custom-prefix">
              <i class="fi-magnifying-glass"></i>
            </span>
          </div>
          <div class="small-11 columns">
            <%= form_tag events_path, method: :get do  %>
              <%= text_field_tag :query, params[:query], :placeholder => "Search for an artist, team or city", class: "hero-input" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

  </section> <!-- -->

  <section class="categories-bg"><!-- -->

    <div class="row">
      <div class="small-6 medium-6 large-3 columns tiles">
        <div class="inner-tile">
          <div class="row">
             <div class="small-12 columns">&nbsp;</div>
          </div>
          <%= link_to static_sport_path do %>
            <p class="change-icon hide-for-touch">
              <span><%= embedded_svg("SportBlue.svg") %></span>
              <span><%= embedded_svg("SportGrey.svg") %></span>
            </p>
            <p class="show-for-touch">
              <span><%= embedded_svg("SportBlue.svg") %></span>
            </p>
          <% end %>
        </div>
      </div>
      <div class="small-6 medium-6 large-3 columns tiles">
        <div class="inner-tile">
          <div class="row">
            <div class="small-12 columns">&nbsp;</div>
          </div>
          <%= link_to category_path(Category.where(description: "Theater").ids) do %>
            <p class="change-icon hide-for-touch">
              <span><%= embedded_svg("TheaterBlue.svg") %></span>
              <span><%= embedded_svg("TheaterGrey.svg") %></span>
            </p>
            <p class="show-for-touch">
              <span><%= embedded_svg("TheaterBlue.svg") %></span>
            </p>
          <% end %>
        </div>
      </div>
      <div class="small-6 medium-6 large-3 columns tiles">
        <div class="inner-tile">
          <div class="row">
            <div class="small-12 columns">&nbsp;</div>
          </div>
          <%= link_to category_path(Category.where(description: "Opera").ids) do %>
            <p class="change-icon hide-for-touch">
              <span><%= embedded_svg("OperaBlue.svg") %></span>
              <span><%= embedded_svg("OperaGrey.svg") %></span>
            </p>
            <p class="show-for-touch">
              <span><%= embedded_svg("OperaBlue.svg") %></span>
            </p>
          <% end %>
        </div>
      </div>
      <div class="small-6 medium-6 large-3 columns tiles">
        <div class="inner-tile">
          <div class="row">
            <div class="small-12 columns">&nbsp;</div>
          </div>
          <%= link_to category_path(Category.where(description: "Concerts").ids) do %>
            <p class="change-icon hide-for-touch">
              <span><%= embedded_svg("ConcertsBlue.svg") %></span>
              <span><%= embedded_svg("ConcertsGrey.svg") %></span>
            </p>
            <p class="show-for-touch">
              <span><%= embedded_svg("ConcertsBlue.svg") %></span>
            </p>
          <% end %>
        </div>
      </div>
    </div>

  </section>

  <div class="row">
      <div class="grid">
        <div class="grid-sizer"></div>
        <div class="gutter-sizer"></div>
        <% # modify line below to change this grid item %>
        <% @grid_item = Competition.find(6) %>
        <%= link_to competition_path(@grid_item) do %>
          <div class="grid-item">
            <%= image_tag @grid_item.avatar.grid_large.url %>
            <span class="image-overlay">
              <span style="color: #2D669A;" class="gotham-regular">
                <%= Category.find(@grid_item.category_id).description %> |
              </span>
              <span class="gotham-regular">
                <%= @grid_item.name %>
              </span>
            </span>
          </div>
        <% end %>
        <% @grid_item = nil %>
        <% # modify line below to change this grid item %>
        <% @grid_item = Competition.find(5) %>
        <%= link_to competition_path(@grid_item) do %>
          <div class="grid-item">
            <%= image_tag @grid_item.avatar.grid_small.url %>
            <span class="image-overlay">
              <span style="color: #2D669A;" class="gotham-regular">
                <%= Category.find(@grid_item.category_id).description %> |
              </span>
              <span class="gotham-regular">
                <%= @grid_item.name %>
              </span>
            </span>
          </div>
        <% end %>
        <% @grid_item = nil %>
        <% # modify line below to change this grid item %>
        <% @grid_item = Player.find(1) %>
        <%= link_to player_path(@grid_item) do %>
          <div class="grid-item">
            <%= image_tag @grid_item.avatar.grid_large.url %>
            <span class="image-overlay">
              <span style="color: #2D669A;" class="gotham-regular">
                <%= Category.find(@grid_item.category_id).description %> |
              </span>
              <span class="gotham-regular">
                <%= @grid_item.name %>
              </span>
            </span>
          </div>
        <% end %>
        <% @grid_item = nil %>
        <% # modify line below to change this grid item %>
        <% @grid_item = Competition.find(2) %>
        <%= link_to competition_path(@grid_item) do %>
          <div class="grid-item">
            <%= image_tag @grid_item.avatar.grid_large.url %>
            <span class="image-overlay">
              <span style="color: #2D669A;" class="gotham-regular">
                <%= Category.find(@grid_item.category_id).description %> |
              </span>
              <span class="gotham-regular">
                <%= @grid_item.name %>
              </span>
            </span>
          </div>
        <% end %>
        <% @grid_item = nil %>
        <% # modify line below to change this grid item %>
        <% @grid_item = Player.find(11) %>
        <%= link_to player_path(@grid_item) do %>
          <div class="grid-item">
            <%= image_tag @grid_item.avatar.grid_large.url %>
            <span class="image-overlay">
              <span style="color: #2D669A;" class="gotham-regular">
                <%= Category.find(@grid_item.category_id).description %> |
              </span>
              <span class="gotham-regular">
                <%= @grid_item.name %>
              </span>
            </span>
          </div>
        <% end %>
        <% @grid_item = nil %>
        <% # modify line below to change this grid item %>
        <% @grid_item = Competition.find(6) %>
        <%= link_to competition_path(@grid_item) do %>
          <div class="grid-item">
            <%= image_tag @grid_item.avatar.grid_large.url %>
            <span class="image-overlay">
              <span style="color: #2D669A;" class="gotham-regular">
                <%= Category.find(@grid_item.category_id).description %> |
              </span>
              <span class="gotham-regular">
                <%= @grid_item.name %>
              </span>
            </span>
          </div>
        <% end %>
        <% @grid_item = nil %>
        <% # modify line below to change this grid item %>
        <% @grid_item = Competition.find(6) %>
        <%= link_to competition_path(@grid_item) do %>
          <div class="grid-item">
            <%= image_tag @grid_item.avatar.grid_large.url %>
            <span class="image-overlay">
              <span style="color: #2D669A;" class="gotham-regular">
                <%= Category.find(@grid_item.category_id).description %> |
              </span>
              <span class="gotham-regular">
                <%= @grid_item.name %>
              </span>
            </span>
          </div>
        <% end %>
        <% @grid_item = nil %>
        <% # modify line below to change this grid item %>
        <% @grid_item = Competition.find(6) %>
        <%= link_to competition_path(@grid_item) do %>
          <div class="grid-item">
            <%= image_tag @grid_item.avatar.grid_large.url %>
            <span class="image-overlay">
              <span style="color: #2D669A;" class="gotham-regular">
                <%= Category.find(@grid_item.category_id).description %> |
              </span>
              <span class="gotham-regular">
                <%= @grid_item.name %>
              </span>
            </span>
          </div>
        <% end %>
        <% @grid_item = nil %>
        <% # modify line below to change this grid item %>
        <% @grid_item = Competition.find(6) %>
        <%= link_to competition_path(@grid_item) do %>
          <div class="grid-item">
            <%= image_tag @grid_item.avatar.grid_large.url %>
            <span class="image-overlay">
              <span style="color: #2D669A;" class="gotham-regular">
                <%= Category.find(@grid_item.category_id).description %> |
              </span>
              <span class="gotham-regular">
                <%= @grid_item.name %>
              </span>
            </span>
          </div>
        <% end %>
        <% @grid_item = nil %>
        <% # modify line below to change this grid item %>
        <% @grid_item = Competition.find(6) %>
        <%= link_to competition_path(@grid_item) do %>
          <div class="grid-item">
            <%= image_tag @grid_item.avatar.grid_large.url %>
            <span class="image-overlay">
              <span style="color: #2D669A;" class="gotham-regular">
                <%= Category.find(@grid_item.category_id).description %> |
              </span>
              <span class="gotham-regular">
                <%= @grid_item.name %>
              </span>
            </span>
          </div>
        <% end %>
        <% @grid_item = nil %>
        <% # modify line below to change this grid item %>
        <% @grid_item = Competition.find(6) %>
        <%= link_to competition_path(@grid_item) do %>
          <div class="grid-item">
            <%= image_tag @grid_item.avatar.grid_small.url %>
            <span class="image-overlay">
              <span style="color: #2D669A;" class="gotham-regular">
                <%= Category.find(@grid_item.category_id).description %> |
              </span>
              <span class="gotham-regular">
                <%= @grid_item.name %>
              </span>
            </span>
          </div>
        <% end %>
        <% @grid_item = nil %>
        <% # modify line below to change this grid item %>
        <% @grid_item = Competition.find(6) %>
        <%= link_to competition_path(@grid_item) do %>
          <div class="grid-item">
            <%= image_tag @grid_item.avatar.grid_small.url %>
            <span class="image-overlay">
              <span style="color: #2D669A;" class="gotham-regular">
                <%= Category.find(@grid_item.category_id).description %> |
              </span>
              <span class="gotham-regular">
                <%= @grid_item.name %>
              </span>
            </span>
          </div>
        <% end %>
      </div>
  </div>

  <script>
    var $grid = $('.grid').masonry({
      itemSelector: '.grid-item',
      percentPosition: true,
      columnWidth: '.grid-sizer',
      gutter: '.gutter-sizer'
    });
    // layout Isotope after each image loads
    $grid.imagesLoaded().progress( function() {
      $grid.masonry();
    });
  </script>

  <script src='/assets/masonry.min.js'></script>
  <script src='/assets/imagesLoaded.min.js'></script>