config/routes.rb
Rails.application.routes.draw do

  resources :messages, only: [:new, :create]

  get 'static/sport'
  get 'static/terms'

  resources :categories, only: [:show, :index]
  resources :competitions, only: [:show, :index]
  resources :events, only: [:show, :index]
  resources :players, only: [:show]
  resources :tickets, only: [:show]

  root 'home#index'

  namespace :admin do
    root 'welcome#index'
    resources :categories
    resources :competitions
    resources :events
    resources :players
    resources :tickets
    resources :venues
  end

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :players, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :competitions, dependent: :destroy

  validates :description, presence: true,
                          length: { maximum: 50 }

  validates :sports, inclusion: { in: [true, false] }

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = "Category successfully created"
      redirect_to [:admin, @category]
    else
      render 'new'
    end
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      flash[:notice] = "Category successfully updated"
      redirect_to [:admin, @category]
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = "Category successfully deleted"
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:description, :sports)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.order('description ASC')
  end

  def show
    @category = Category.find(params[:id])
    @players = Player.where(category_id: @category.id).order('name ASC')
    @competitions = Competition.where(category_id: @category.id).order('name ASC')
    @events = Event.where(category_id: @category.id).order('start_time ASC')
  end

end

app/views/categories/index.html.erb
<div class="row gotham-regular">
  <ul class="breadcrumbs">
    <li><%= link_to 'Home', root_url %></li>
    <li class="current">Categories</li>
  </ul>
</div>

<section class="categories-bg-index">
  <div class="row">
    <% @categories.each do |category| %>
      <div class="small-6 medium-6 large-3 columns tiles-index">
        <div class="inner-tile">
          <div class="row">
             <div class="small-12 columns">&nbsp;</div>
          </div>
          <%= link_to category_path(category) do %>
          <p class="change-icon hide-for-touch">
            <% if has_icon?(category.description) != false %>
              <span><%= embedded_svg("#{has_icon?(category.description)}Blue.svg") %></span>
              <span><%= embedded_svg("#{has_icon?(category.description)}Grey.svg") %></span>
            <% else %>
              <h5 class="gotham-regular" style="color: #2D669A;"><%= category.description %></h5>
            <% end %>
          </p>
          <p class="show-for-touch">
            <% if has_icon?(category.description) != false %>
              <span><%= embedded_svg("#{has_icon?(category.description)}Blue.svg") %></span>
            <% else %>
              <h5 class="gotham-regular" style="color: #2D669A;"><%= category.description %></h5>
            <% end %>
          </p>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/categories/show.html.erb
<div class="row gotham-regular">
  <ul class="breadcrumbs">
    <li><%= link_to 'Home', root_url %></li>
    <li><%= link_to 'Categories', categories_path %></li>
    <li class="current"><%= @category.description %></li>
  </ul>
</div>

<div class="row">
  <div class="small-12 columns">
    <h3 class="gotham-regular"><%= @category.description %></h3>
  </div>
</div>

<% if @competitions.count > 0 %>

<div class="row">&nbsp;</div>

<div class="row table">
  <div class="small-12 columns">
    <% @competitions.each do |competition| %>
      <div class="row mini-table-row">
        <div class="small-10 columns mini-table-one">
          <h5 class="gotham-regular" style="font-size: 1rem; color: #2D669A;"><%= competition.name %></h5>
        </div>
        <%= link_to competition_path(competition) do %>
          <div class="small-2 columns mini-table-two text-center">
            <h5 class="gotham-regular table-link">View</h5>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<div class="row">&nbsp;</div>

<% elsif @players.count > 0 %>

<div class="row">&nbsp;</div>

<div class="row table">
  <div class="small-12 columns">
    <% @players.each do |player| %>
      <div class="row mini-table-row">
        <div class="small-10 columns mini-table-one">
          <h5 class="gotham-regular" style="font-size: 1rem; color: #2D669A;"><%= player.name %></h5>
        </div>
        <%= link_to player_path(player, :comp => @competition) do %>
          <div class="small-2 columns mini-table-two text-center">
            <h5 class="gotham-regular table-link">View</h5>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<div class="row">&nbsp;</div>

<% elsif @events.count > 0 %>

<div class="row">&nbsp;</div>

<div class="row table">
  <div class="small-12 columns">
    <% @events.each do |event| %>
      <div class="row table-row">
        <div class="small-3 columns table-one">
          <h5 class="gotham-regular" style="font-size: 1rem;"><%= event.start_time.strftime("%a") %></h5>
          <h5 class="gotham-light"><%= event.start_time.strftime("%d %b %Y") %></h5>
          <h5 class="gotham-light" style="color: #A8A8A8;"><%= event.start_time.strftime("%H:%M") %></h5>
        </div>
        <div class="small-7 columns table-two">
          <h5 class="gotham-regular" style="font-size: 1rem; color: #2D669A"><%= event.name %></h5>
          <h5 class="gotham-light"><%= event.venue.name %></h5>
          <h5 class="gotham-light" style="color: #A8A8A8;"><i class="fi-marker"></i><%= " #{event.venue.city}, #{event.venue.country}" %></h5>
        </div>
        <div class="small-2 columns table-three">
          <%= link_to 'Tickets', '#', class: 'button tiny radius' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="row">&nbsp;</div>

<% else %>

<div class="row">&nbsp;</div>

<div class="row">
  <div class="small-12 columns">
      <p class="gotham-regular">Can't find what you’re looking for?</p>
      <p class="gotham-light">Ticketfinders has been finding our clients sold out and hard to get tickets to events all around the World for over 40 years and we encourage you to send us a message if you can’t find what you’re looking for on our site.</p>
      <p class="gotham-light">So please send us a quick message and we’ll get back to you as soon as we can.</p>
      <%= link_to 'Contact Us', new_message_path, data: { no_turbolink: true }, class: "button" %>
      </p>
  </div>
</div>

<div class="row">&nbsp;</div>

<% end %>